### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by alperyilmaz** [dommmel/jekyll-youtube#2]
The text following the embed is too close to the iframe. How can we fix this?

![selection_237](https://cloud.githubusercontent.com/assets/410615/15095412/bfd21e30-14cd-11e6-9a14-c8568f75b952.png)

**Comment by dommmel** [comment]
Use css to add some whitespace. You can also change the default markup as described here:
https://github.com/dommmel/jekyll-youtube#result
