### ISSUE TITLE
It does not work with git pages

### ISSUE THREAD

**Issue by adriano-fonseca** [dommmel/jekyll-youtube#4]
I try to use this nice plugin. And everything is working fine locally. However, when I push my changes to git pages, I got **"The tag `youtube` on line 5 in `_posts/2017-02-10-Generating-token-docker-machine-aws-do.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/."**, any help will be welcome :)

Here is my repository https://github.com/adriano-fonseca/adriano-fonseca.github.io

**Comment by dommmel** [comment]
Github Pages does not support plugins other than a few whitelisted ones.

See https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
