### ISSUE TITLE
Allow options

### ISSUE THREAD

**Issue by ericktucto** [dommmel/jekyll-youtube#6]
## Autoplay
{% youtube "https://www.youtube.com/watch?v=ho8-vK0L1_8?autoplay=0" %}

## Showinfo
{% youtube "https://www.youtube.com/watch?v=ho8-vK0L1_8?showinfo=0" %}

**Example**
{% youtube "https://www.youtube.com/watch?v=ho8-vK0L1_8" showinfo %}
{% youtube "https://www.youtube.com/watch?v=ho8-vK0L1_8" autoplay %}

**Comment by dommmel** [comment]
Pull requests welcomed
